version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
    restart: unless-stopped
    networks:
      - voice-chat-network

  frontend:
    image: nginx:alpine
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx-ssl.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - voice-chat-network

networks:
  voice-chat-network:
    driver: bridge
